[build-system]

requires = ["setuptools",
            "wheel",
            # Require numpy>=1.20.3 on Windows due to https://github.com/numpy/numpy/pull/16468
            "oldest-supported-numpy; python_version=='3.10' or platform_system!='Windows'",
            "numpy==1.20.3; python_version<'3.10' and platform_system=='Windows'",
            # FIXME: https://github.com/scipy/oldest-supported-numpy/pull/61 not yet released
            "numpy==1.23.2; python_version=='3.11'"]

build-backend = 'setuptools.build_meta'
